services:
  springboot:
    image: bhargav11413/spring-app:1.0
    container_name: spring-boot-app
    restart: always
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=example
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - springappnetwork

  mongo:
    image: mongo:4.4
    container_name: mongodb-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: users
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - springappnetwork

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - springappnetwork

volumes:
  mongodb_data:

networks:
  springappnetwork:
    driver: bridge
